ports:
- port: 8080
  onOpen: open-preview
tasks:
- name: LAMP
  init: sudo chmod 777 -R www && docker run -p "8080:80" -v ${PWD}/www:/app mattrayner/lamp:latest-2004-php8

- name: Docker Terminal
  init: docker exec -it peaceful_franklin /bin/bash
